baseurl = "/"
languageCode = "en-us"
title = "Sweiss' Blog"
theme = "hugo-lithium-theme"
googleAnalytics = "UA-143180066-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Sam Weiss"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/samcarlos"

[[menu.main]]
    name = "r-bloggers"
    url = "https://www.r-bloggers.com/"

[params]
    description = "A website I use to throw up my stats stuff"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

[context.production.environment]
    HUGO_VERSION = "0.30.2"
